name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Ustawienie Pythona
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      # 3. Instalowanie zależności
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 black

      # 4. Uruchomienie lintowania (SuperLinter)
      - name: Run SuperLinter for Python
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: true
          LINTER_RULES_PATH: .github/linters

      # 5. Uruchomienie testów z raportem o pokryciu
      - name: Run tests and generate coverage report
        run: |
          pytest --cov=main --cov-report=xml

